### ISSUE TITLE
Calculating scale factor for a custom Transverse Mercator projection

### ISSUE THREAD

**Issue by mikatanmeijia** [GIS4DEV/Q-and-A#3]
Hello, I'm working on Madagascar that is 7.3 degrees longitude wide, so a UTM projection (for 6-degrees-wide blocks) would be insufficiently accurate as a projection. 

I created my own Transverse Mercator projection, where lon_0 is the middle meridian of the country, lon_1 is one-sixths away from xMin towards lon_0, and lon_2 is one-sixths away from xMax towards lon_0. The proj.4 reads like this:

+proj=tmerc +lat_0=-18.7775 +lon_0=46.83735 +lon_1=44.404583 +lon_2=49.270116 +k=0.9996 +x_0=2000000 +y_0=2000000 +ellps=WGS84 +datum=WGS84 +units=m +no_defs

**1. Scale factor?**
I used +k=0.9996. I found this number as a default k_0 from [this discussion thread.](http://forums.esri.com/Thread.asp?c=93&f=984&t=277480) The value for +k will be 1 if +k is not specified. In this case, how should I calculate k, or does specifying lon_1 and lon_2 work around the scaling somewhat?

**2. lon_1 and lon_2**
Is the one-sixth/two-thirds/one-sixth division optimal for Madagascar?

**or, would an oblique transverse Mercator work better because of the 'slanted island' geography of Madagascar?**

Any help would be appreciated, thanks! (:

Mika

**Comment by MartinWF** [comment]
As for question 1, I'd use the excel spreadsheet formula that Dr. Holler uploaded on Moodle. You enter the  values required, and it provides you with a k factor customized for your country.

In terms of question 2, I used one-fourth/one-half/one-fourth for Benin, as I mentioned earlier today.

**Comment by josephholler** [comment]
To follow up on the optimal ratios for the standard lines, I still have not seen an optimal guideline for transverse mercator anywhere.  But, looking at transverse mercator projections for UTM, state plane zones, and a Mississippi projection, Martin and I concluded that most of the ratios are closer to 1/4 - 1/2 - 1/4.  

Regarding how to customize a transverse mercator projection, you can only set the central meridian and a scale factor at the central meridian.  If you use the spreadsheet I provided, you can solve for a scale factor _k_ at the central meridian, given a scale factor of 1 (no distortion) at a distance _x_ away from the central meridian.  To use the formula, first figure out the linear distance _x_ you want in between the central meridian and your standard lines.

The reason why you cannot set a lon_1 and lon_2 for transverse mercator is that the longitudes are not parallel-- the distance between them is greater at the equator and 0 at the poles.  This is why a conic projection is so convenient for E/W countries, because you can set the 2 standard lines at the lat_1 and lat_2 parallels.

Are any of you quick with javascript?  It'd be nice to put an interactive javascript version of the transverse mercator scale formula online...

**Comment by mikatanmeijia** [comment]
Ah, I finally understand k_0 and k_x! Thank you both! I now have my custom transverse mercator projection (:

(Sorry I can't do javascript...)
