### ISSUE TITLE
Spatial extent from m

### ISSUE THREAD

**Issue by MartinWF** [GIS4DEV/Q-and-A#4]
I'm doing the metadata for my custom projection, and while WGS 84 provided the spatial extents in coordinates (xMin, xMax, yMin, and yMax), I'm now getting them in meters. Is it okay to enter these in the metadata table? If not, how might I translate these into coordinates? Thank you!

**Comment by josephholler** [comment]
To document the original state of the data, if you have any version of your geographic data that is still in a geographic coordinate system, add that to the QGIS map and look at the layer properties.  Otherwise, setting the project properties to use a geographic coordinate system and projection on the fly will allow you to estimate the extent by looking at the coordinates in the status bar.

In a repository of geographic data, the metadata would keep the extent stored in latitude and longitude coordinates so that datasets could be searched based on location criteria.

For your projects, it's also useful to look at your spatial extent in meters after you create a new custom projection, because this will help you figure out if you set your origin and false origin (cartographic offset) correctly.

**Comment by MartinWF** [comment]
That makes sense - thank you!
