### ISSUE TITLE
How do I hack Q on my mac? Here's how!

### ISSUE THREAD

**Issue by jeanniebartlett** [GIS4DEV/Q-and-A#6]
I wanted to force-add my custom projection into the QGIS system on my mac, as Joe describes in the end of Lab03. But because mac os 'bundles' applications, you can't easily connect to the srs.db. But I figured out how to do it! 

First, you can SEE the contents of Q's app bundle in Finder by right-clicking on the app in the "Applications" folder, and selecting "Show Package Contents." From there you can drill down to find srs.db.

But when you're in Q's gui for connecting to a new database, there's no way to "show package contents." There's no way to get to the system files through Q.

So here's what I did:

First I made a back-up copy of Q.

In Finder, I right-clicked on one of the copies and selected "Get Info." Under the "Names and Extensions" section of the window that pops up, you'll see "qgis.app". Simply remove the ".app" extension from the name, hit enter, and confirm that you want to make it "just a folder."

Then open the plain folder, and inside Contents>MacOS you'll find a Unix Executable File called "QGIS." Double-click this, and QGIS should open and run (Terminal will also open--leave this window open and don't do anything with it until you're all done.)

In QGIS, make a new SpatiaLite database connection as you normally would, finding the srs.db under your QQGIS folder>Contents>resources>resources>srs.db

Follow Joe's Lab03 instructions for inserting your custom projection into the tbl_srs. Make sure it added properly.

Close QGIS. Back in Finder, add the ".app" extension back onto the folder, and confirm that you want to bundle it. Personally, I kept both copies of Q, and added my initials to the end of the one I hacked so that I can continue to mess with it and keep a clean copy.

Hooray!
For more info on application bundles, see this article. It was super useful to me: http://www.mactipsandtricks.com/website/articles/Wiley_HT_appBundles2.lasso

**Comment by josephholler** [comment]
Thanks, Jeannie!  For all of you Mac users, do you think this would be any easier if you were logged in to your Mac OS as a power user or administrator?  I'm sorry I do not know more about Mac OS in order to help you with this...

Also, as long as the only SQL you are using is an `INSERT INTO` statement, you don't run a risk of corrupting the database.  If you've chosen an `SRID` that matches an existing `SRID`, the command should fail.  If you've entered an incorrect projection, the worst that will happen is that your custom projection won't work.
